source "https://rubygems.org"

gem "sinatra"
gem 'thin', '1.6.2'
gem "sinatra-contrib"
gem "sinatra-assetpack"
gem "sinatra-static-assets"
gem "sinatra-flash"
gem "libxml-ruby"
gem "gpx"
gem "haversine"
gem "ruby-units"
gem "gruff"
